version: '3'
services:
  agent:
    image: hugojf/docker-ogpagent
    restart: always
    networks:
        - nfs_broadcasts
        - public_ip_network
    ports:
      - "${OGP_LISTEN_PORT:-12679}:12679/tcp"
      - "27015:27015/tcp"
      - "27015:27015/udp"
    security_opt:
        - apparmor:unconfined
    cap_add:
        - CAP_SYS_ADMIN
        - NET_ADMIN
        - LINUX_IMMUTABLE
    environment:
      - GATEWAY=${GATEWAY:-router}
      - NFS_SERVER=${NFS_SERVER}
      - OGP_LOGFILE=/opt/OGP/ogp_agent.log
      - OGP_LISTEN_PORT=12679
      - OGP_LISTEN_IP=0.0.0.0
      - OGP_VERSION=v3372
      - OGP_KEY=encryption_key2
      - OGP_STEAM_LICENSE=Accept
      - OGP_SUDO_PASSWORD=ogpuser
      - OGP_SCREEN_LOG_LOCAL=1
      - OGP_DELETE_LOGS_AFTER=30
      - OGP_OGP_MANAGES_FTP=1
      - OGP_FTP_METHOD=PureFTPd
      - OGP_AUTORESTART_SERVER=1
networks:
    public_ip_network:
        external:
            name: '${PUBLIC_IP_NETWORK}'
    host_network:
        external:
            name: host

    nfs_broadcasts:
        external:
            name: nfs_broadcasts
