version: '2'
services:
  agent:
    image: joshhsoj1902/docker-ogpagent
    restart: always
    ports:
      - "12679:12679/tcp"
      - "27015:27015/udp"
      - "7778:7778/udp"
      - "32330:32330/tcp"
    volumes:
      - ./ogp_agent/games:/home/ogp_agent/OGP_User_Files
